#
#
# VARIABLES  
variable T         equal  0.50 #0.10 0.36 0.70    
variable num       equal  1 
variable N         equal  10 #200 # 250 300 350 
variable box       equal  50 
variable t_step    equal  0.005 
variable mix_steps equal  200000 
variable mix_tau   equal  ${t_step}*${mix_steps} 
variable run_steps equal  2000000
variable run_tau   equal  ${t_step}*${run_steps} 

# PARAMETERS    
units lj
atom_style molecular
neighbor 0.4 bin
neigh_modify every 1 delay 1 check yes
comm_modify vel yes

# READ  
read_data input_data_nunchucks_${N}_${box}.file

#  BONDS 
bond_style harmonic
special_bonds lj 0 1 1
bond_coeff * 500.0 0.98  # the wildcard (*) means to have the same for all bond types.   

# ANGLES  
angle_style harmonic
angle_coeff * 500.0  180

# PAIR lj/cut --with interactions, to steady state
pair_style lj/cut 1.0
pair_modify shift yes
pair_coeff * * 1  1.0  1.12

# THERMAL   
timestep ${t_step}
thermo   100 
thermo_style custom step time temp press pe ke etotal vol
thermo_modify norm no
reset_timestep 0

# FIX
fix 4 all nve 
fix 5 all langevin ${T} ${T} 1 123456 
fix recen1 all recenter INIT INIT INIT


# DUMP OUTPUT 
dump  1  all custom 1000 output.dump id mol type x y z vx vy vz

# FIX for RDF
#comm_modify cutoff 25.0
#compute   3 all rdf 500 5 6 cutoff 24.0
#fix       3 all ave/time 1 ${run_steps} ${run_steps} c_3[*] file rdf_T_${T}_N_${N}_box_${box}_tau_${run_tau}.rdf mode vector


# RUN
run ${run_steps}

# SHELL
shell cp output.dump        output_T_${T}_N_${N}_box_${box}_run_${run_tau}_tau_num_${num}.dump
shell touch T_${T}.done

#clear
#next T
#jump in.run

